# Generated by Django 5.1.7 on 2025-04-05 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='meallog',
            name='food_item',
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='meallog',
            name='quantity_in_grams',
        ),
        migrations.AddField(
            model_name='meallog',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meallog',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meallog',
            name='protein',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meallog',
            name='total_calories',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meallog',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FoodItem',
        ),
    ]
