# Generated by Django 5.1.7 on 2025-04-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_alter_meallog_food_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meallog',
            name='food_item',
        ),
        migrations.RemoveField(
            model_name='meallog',
            name='user',
        ),
        migrations.AddField(
            model_name='meallog',
            name='food_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
