# Generated by Django 5.1.7 on 2025-04-05 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_remove_meallog_food_item_remove_meallog_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meallog',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
