# Generated by Django 5.1.7 on 2025-04-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_meallog_user_alter_meallog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='meallog',
            name='food_image',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='carbs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='protein',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='total_calories',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
