# Generated by Django 5.1.7 on 2025-04-11 03:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_meallog_food_image_alter_meallog_carbs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meallog',
            name='food_image',
        ),
        migrations.AddField(
            model_name='meallog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='meal_images/'),
        ),
        migrations.AddField(
            model_name='meallog',
            name='quantity',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='meallog',
            name='time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='meallog',
            name='unit',
            field=models.CharField(default='grams', max_length=20),
        ),
    ]
